### ISSUE TITLE
How to deal with ‘red’ CI for transitive dependencies?

### ISSUE THREAD

**Issue by alloy** [dependencyci/support#1]
Currently [the CI status on one of our repos is red](https://dependencyci.com/github/artsy/emission/builds/5) because somewhere in our NPM dependency graph we depend on some deprecated packages. While I sympathise with the idea of patching those dependencies that lead to these deprecated dependencies, that is not necessarily something I want to be doing _at this very moment_.

I understand that the GitHub Statuses API currently does not provide a _warning_ status, so it needs to be communicated through _failure_, but would it be possible to selectively mute warnings for packages from the CI build page?

**Comment by andrew** [comment]
You can use `dependencyci.yml` to skip certain dependencies: https://dependencyci.com/docs

**Comment by alloy** [comment]
Doh, of course. Thanks for the pointer 👍

**Comment by alloy** [comment]
Should this config file be working https://github.com/artsy/emission/pull/203 ?
