### ISSUE TITLE
.NET Core NuGet dependencies

### ISSUE THREAD

**Issue by stofte** [dependencyci/support#10]
Hello,

Does DependencyCI work with .NET Core? I'm not sure of how to configure my repo to get any info.

https://dependencyci.com/github/stofte/ream-query/builds/1

The project contains multiple NuGet.config and project.json files for resolving deps.

**Comment by andrew** [comment]
Hi, it currently supports project.json files in the root of the repository. I'll update it so that it handles them within folders and add parsing of NuGet.json within the new few days.

**Comment by andrew** [comment]
@stofte I've fixed it finding nested project.json files for you now, will leave this open as I've still to add support for NuGet.config

**Comment by andrew** [comment]
At it appears that NuGet.config doesn't actually hold any dependency information itself so there's no need to parse that, going to close this for now.

**Comment by ThePadawan** [comment]
@andrew Does DependencyCI run an exhaustive search for project.json? Without any configuration, it seems like it doesn't detect the project.json files in this repo: https://dependencyci.com/github/ThePadawan/the_diary/builds/535

General project structure:
/
-- package.json
...
/backend/A/
-- project.json
/backend/B/
-- project.json
