### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by zoenolan** [dependencyci/support#12]
We host our git repos on an internal gitlab instance, is that a use case you intend to support?

**Comment by andrew** [comment]
@zoenolan eventually yes, in the short term I think the API will be finished before hand so you might be able to use that with GitLab to check dependencies before the proper GitLab integration is finished.

**Comment by outsmartin** [comment]
We would also be very interested in a gitlab integration.

**Comment by zoenolan** [comment]
rather than keeping this open for ever, closing this after three years
