### ISSUE TITLE
Internal error for html5ever

### ISSUE THREAD

**Issue by jdm** [dependencyci/support#15]
https://dependencyci.com/github/servo/html5ever shows a failed build, but clicking on the failure leads to an internal error page.

**Comment by andrew** [comment]
I've fixed that now @jdm, I didn't realise you could do this in `Cargo.toml`: 

```toml
heapsize = { version = ">=0.1.1, <0.4", optional = true }
```

Will get that fixed up soon

**Comment by jdm** [comment]
Thanks!
