### ISSUE TITLE
Support for multiple requirement.txt files for python.

### ISSUE THREAD

**Issue by mhubig** [dependencyci/support#19]
I have three different `requirement.txt` files in the root of my python project. `dependencyci.com` is just detecting one of them ...

See: https://dependencyci.com/github/mhubig/implib2/builds/1

**Comment by andrew** [comment]
I've just rolled out an update that should fix this, can you rerun your last build or push to github to see if it's working?

**Comment by mhubig** [comment]
It's working now!

See: https://dependencyci.com/github/mhubig/implib2/builds/3

**Comment by andrew** [comment]
Wonderful!
