### ISSUE TITLE
Support for multi-tier Python dependencies

### ISSUE THREAD

**Issue by rdmurphy** [dependencyci/support#20]
This may be a variation of #19.

I have a [Python project](https://github.com/rdmurphy/django-template) with both a root level `requirements.txt` file and a `requirements` directory with three `*.txt` files inside. (Somewhat following the style you typically see in Heroku-ish deploys.)

It appears DependencyCI is [only seeing my root `requirements.txt`](https://dependencyci.com/github/rdmurphy/django-template/builds/1) (which references another `requirements` file) and stops there. Should it see both arrangements and check them both? Or is there a configuration option I've missed to address it?

Thank you!

**Comment by andrew** [comment]
Just rolled out an updated to https://github.com/librariesio/bibliothecary, it should find all your requirements.txt files now, you can rerun the build or push to github to check.

**Comment by rdmurphy** [comment]
Awesome! Can confirm it now [finds them all](https://dependencyci.com/github/rdmurphy/django-template/builds/1). Thanks!

**Comment by andrew** [comment]
Brilliant!
