### ISSUE TITLE
A private repo doesn't show in my list of repos

### ISSUE THREAD

**Issue by joshk** [dependencyci/support#21]
Hi Fantastic Dependency CI Peeps

A person on our team started a trial, and enabled a private repo for our org (travis-ci), but I can't find it in my list of repos.

I have clicked resync a few times, but to no avail.

Thanks a bundle

Josh

**Comment by andrew** [comment]
Hey @joshk, are you an "admin" on that repo? I'll have a poke around and see what I can see?

**Comment by joshk** [comment]
All fixed via email

Thanks @andrew !
