### ISSUE TITLE
Documentation page's anchor tag for Dependency Tests

### ISSUE THREAD

**Issue by JuanitoFatas** [dependencyci/support#25]
<img width="841" alt="screenshot 2016-07-13 20 02 34" src="https://cloud.githubusercontent.com/assets/1000669/16802721/cc2ed718-4934-11e6-92f1-50b5aec505c8.png">

The outter div's attribute should be `id="tests"` instead of `class="#tests"` 🔎 .

**Comment by andrew** [comment]
Good spot, I've fixed that now, thanks!
