### ISSUE TITLE
Unknown error on build

### ISSUE THREAD

**Issue by domudall** [dependencyci/support#31]
Not quite sure where to report this. Clicking on a specific build only provides a "An error occurred" message with no details.

https://dependencyci.com/github/ConnectedVentures/f8-transactional-api/builds/7

![image](https://cloud.githubusercontent.com/assets/524482/16807451/5f5b1c60-4910-11e6-9c06-cb8374addea1.png)

**Comment by domudall** [comment]
Just noticed this is a duplicate of #14

**Comment by andrew** [comment]
@domudall I've fixed the build errors now and reran the erroring builds.
