### ISSUE TITLE
NPM shrinkwrap cache invalidation failure?

### ISSUE THREAD

**Issue by Xanderite** [dependencyci/support#36]
Hey,

So just started removing/updating some dependencies from a npm package (its private so can't share it here) and we're getting a report that shows packages that we've removed as a failed dependency (e.g. isparta) even though a quick find in the shrinkwrap json yields no results, is this some unexplained feature or is it definitely a bug of some kind?

Thanks

**Comment by andrew** [comment]
@Xanderite no that sounds like a bug, I'll see if I can replicate it, was this on a feature branch or the default branch?

**Comment by Xanderite** [comment]
Hey there, yeah it was a feature branch if that helps. Again sorry for the lack of replicability. If would help I could PM you a link to the failing test on dependencyci, and the npm-shrinkwrap.json file?

**Comment by andrew** [comment]
You could email me, support@dependencyci.com

**Comment by Xanderite** [comment]
Email sent, thanks for your time.

**Comment by Xanderite** [comment]
A fix has been deployed that resolves this issue.

**Comment by andrew** [comment]
🎉
