### ISSUE TITLE
Allow user to specify package config in non-root directory

### ISSUE THREAD

**Issue by jsachs** [dependencyci/support#38]
For example, my current project has NodeJS package.json files in both `client` and `backend` directories. The DependencyCI tests run on the root directory so no tests are actually run against dependencies.

**Comment by andrew** [comment]
@jsachs I've just enabled that for you, it should look for package.json files everywhere instead of just the root, except inside any folders called `node_modules`, give it a try!

**Comment by jsachs** [comment]
Awesome, thanks @andrew.
