### ISSUE TITLE
Support for GitLab

### ISSUE THREAD

**Issue by aitchkhan** [dependencyci/support#46]
Hi, I am working for a software company, which uses GitLab as its VCS. Do you guys plan to integrate dependency-ci with GitLab. Looking forward to it.

Thanks, 
Haroon Khan.

**Comment by andrew** [comment]
@aitchkhan yeah it's in the pipeline, I'm also working on a way of integrating Dependency CI into existing CI systems which won't be tied directly to GitHub which will land first and should work great with GitLab CI

**Comment by libeclipse** [comment]
This issue is already open. #12
