### ISSUE TITLE
Blank screen - no repos

### ISSUE THREAD

**Issue by driesvints** [dependencyci/support#5]
I get a blank screen when I visit my repositories. I should definitely see some repos here.

![screen shot 2016-07-12 at 13 28 47](https://cloud.githubusercontent.com/assets/594614/16765543/eaa9c136-4834-11e6-8efa-679df1d62fea.png)

ps: sorry for posting twice. First one was with the wrong account.

**Comment by driesvints** [comment]
Do you need "write" permissions before repos show up here?

**Comment by andrew** [comment]
That's very strange, I can't see your account in the database, can you try signing in a different browser?

**Comment by driesvints** [comment]
Fyi: I registered with another account: beatdeploy

**Comment by driesvints** [comment]
I now also signed up with this Github account and I can now see repos. No idea why it does not work for the other user.

**Comment by andrew** [comment]
It doesn't look `beatdeploy` has any public repos, you need to start a free trial to see private repositories

**Comment by driesvints** [comment]
That's true. No public repos. My trial is already started from what I can tell:

![screen shot 2016-07-12 at 15 35 51](https://cloud.githubusercontent.com/assets/594614/16768867/6e6178dc-4846-11e6-83ae-b059e21bf3b9.png)

**Comment by andrew** [comment]
Sorry about that, you found a bug! I've fixed that now, can you go to https://dependencyci.com/enable_private which should enable your private repos

**Comment by driesvints** [comment]
Done. No repos yet.

**Comment by driesvints** [comment]
Fyi: There are two apps now in the settings screen:

![screen shot 2016-07-12 at 15 47 11](https://cloud.githubusercontent.com/assets/594614/16769193/f50b01ae-4847-11e6-9f29-92b1ec3b20df.png)

**Comment by andrew** [comment]
@driesvints the account needs to have permission to manage webhooks on the repos, i.e. admin, to be able to use the service.

**Comment by driesvints** [comment]
aha! ok, now they're showing up. Thanks for helping out :)

Perhaps it's best that you set an explicit notice on the repository screen that says you need admin access.

**Comment by andrew** [comment]
@driesvints agreed, I'll add that to my FAQs, thanks!
