### ISSUE TITLE
False positive: unlicensed bower dependency

### ISSUE THREAD

**Issue by Rudloff** [dependencyci/support#53]
Hello,

In [this build](https://dependencyci.com/github/quai10/quai10-template/builds/1), it complains that knacss is unlicensed, but knacss 4.3 does have a valid license property in its bower.json.

**Comment by Rudloff** [comment]
Same thing here: https://dependencyci.com/github/Rudloff/mls-cell-map/builds/1
leaflet-info-control does have a valid license.

**Comment by mabbas85** [comment]
Same problem here: https://dependencyci.com/github/jenkinsci/gitlab-plugin/builds/3

**Comment by andrew** [comment]
@mabbas85 I've updated the license for that library, builds should pass now

**Comment by Rudloff** [comment]
This seems to be fixed for the two dependencies I mentionned.

**Comment by mreichel** [comment]
It is fixed for the gitlab-plugin. Thanks!
