### ISSUE TITLE
Does not use the relevant build.gradle

### ISSUE THREAD

**Issue by dschuermann** [dependencyci/support#6]
Dependency CI uses the main build.gradle but does not find the other much more important gradle files. As an example: https://dependencyci.com/github/open-keychain/open-keychain/builds/1 use the main build.gradle but not https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/build.gradle (this is a multi-project build).

**Comment by andrew** [comment]
I've just rolled out an update that should fix dependency ci skipping the extra build.gradle files, can you try rerunning the last build or pushing to GitHub to see if it's worked?

**Comment by dschuermann** [comment]
great works.
