### ISSUE TITLE
Support multiple packages.config for C# + NuGet

### ISSUE THREAD

**Issue by ThePadawan** [dependencyci/support#7]
Example project : https://dependencyci.com/github/ThePadawan/the_diary

DependencyCI so far only analyzes backend/TheDiary.TestServerApp/packages.config, and disregards all other packages.config in backend/. These other projects contain other dependencies, which are currently not analyzed.

Example dependency I expect to see: TheDiary.Dal references FluentNHibernate.

**Comment by andrew** [comment]
I've just rolled out an update that should fix dependency ci skipping the extra packages.config files, can you try rerunning the last build or pushing to GitHub to see if it's worked?

**Comment by ThePadawan** [comment]
I've just kicked off analysis 3: https://dependencyci.com/github/ThePadawan/the_diary/builds/3

This has correctly analyzed all packages.config. Thank you for getting on this so quickly!

**Comment by andrew** [comment]
Excellent!
