### ISSUE TITLE
Commit status pending forever

### ISSUE THREAD

**Issue by indirect** [dependencyci/support#72]
There is a specific commit that Dependency CI has marked as pending, and never marked as either success or failure: https://github.com/rubygems/rubygems.org/commit/ece683b898f3d431186e1a2c5c2b49648c34df55. This has happened to us several times in the past, and interferes a lot with our deploy system, which only wants to deploy a commit if it has a passing status.

My theory is that it is because that commit was first pushed to the `auto` branch, and then later pushed to the `master` branch. Would that cause this kind of problem? Thanks!

**Comment by andrew** [comment]
@indirect sorry about that, I'll check that out first thing in the morning

**Comment by indirect** [comment]
@andrew any updates?

**Comment by indirect** [comment]
@andrew ping, any chance this is resolved yet?

**Comment by andrew** [comment]
@indirect it looks like every so often `message_bus` is filling up the redis instance with session data which causes issues for the sidekiq queue. 

New builds from the github webhook update their status on github and are then pushed to the redis queue where they then get started doing the actual work, unless redis is full then they just disappear 😱 

I've bumped up the redis memory but also going to change the way the builds update their github status so they don't say they've started until they actually do, also going to add in a regular sweeper task to make sure none get left in a stuck case in the mean time.

Sorry for that, I've only been able to work on Dependency CI in my spare time the past couple months as I'm working on Libraries.io full time now: https://medium.com/@teabass/libraries-io-joins-brave-new-software-c8cb7bba93bf

**Comment by indirect** [comment]
Aha! Thanks for figuring this out! <3
