### ISSUE TITLE
npm packages are incorrectly listed as deprecated

### ISSUE THREAD

**Issue by lukechilds** [dependencyci/support#81]
One of my packages browser-env is being incorrectly listed as deprecated. I have previously deprecated specific versions with bugs to warn people to update. It seems like maybe this is being incorrectly interpreted as the package being deprecated forever.

You can see when-dom-ready fails due to the dependency on browser-env:

https://dependencyci.com/github/lukechilds/when-dom-ready/builds/1

Are you using the libraries.io API? They seem to have the same issue: https://github.com/librariesio/libraries.io/issues/1247

**Comment by andrew** [comment]
I've fixed that for you, thanks for letting me know
