### ISSUE TITLE
How can I update my plan from Personal to Organization?

### ISSUE THREAD

**Issue by ShibataTakao** [dependencyci/support#84]
I'd like to update my plan from Personal to Organization.
But I can't find any way to do it on https://dependencyci.com/settings/ShibataTakao .

Pleate tell me how to upldate my plan.

**Comment by ShibataTakao** [comment]
@andrew What's the status now?

**Comment by andrew** [comment]
@ShibataTakao I've emailed you with an update

**Comment by ShibataTakao** [comment]
@andrew Thank you for your reply.
I've emailed you again. So please check and answer it.

**Comment by ShibataTakao** [comment]
@andrew What's the status now?

**Comment by andrew** [comment]
@ShibataTakao I've just replied to your email
